sudo: required
services:
    - docker

before_install:
    - docker build -t alfredhawkman/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run alfredhawkman/react-test npm test -- --coverage

after_success:
    - docker build -t alfredhawkman/multi-client ./client
    - docker build -t alfredhawkman/multi-nginx ./nginx
    - docker build -t alfredhawkman/multi-server ./server
    - docker build -t alfredhawkman/multi-worker ./worker
    # login into docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # push images to dockerhub
    - docker push alfredhawkman/multi-client
    - docker push alfredhawkman/multi-nginx
    - docker push alfredhawkman/multi-server
    - docker push alfredhawkman/multi-worker

deploy:
    provider: elasticbeanstalk
    region: eu-west-2
    app: multidocker
    env: Multidocker-env
    bucket_name: elasticbeanstalk-eu-west-2-368943693201
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: $AWS_SECRET_KEY